SubscriptionTracker/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using SubscriptionTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SubscriptionTracker.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly IExpenseRepository _expenseRepository;

        public ExpenseController(IExpenseRepository expenseRepository)
        {
            _expenseRepository = expenseRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddExpense(Expense expense)
        {
            if (_expenseRepository.AddExpense(expense))
            {
                return View("Index");
            }
            else
            {
                return View("/Views/Shared/Error.cshtml");
            }
        }
    }
}

SubscriptionTracker/Controllers/RegisterCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SubscriptionTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SubscriptionTracker.Controllers
{
    public class RegisterCustomerController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICustomerRespository _customerRespository;

        public RegisterCustomerController(ILogger<HomeController> logger, ICustomerRespository customerRespository)
        {
            _logger = logger;
            _customerRespository = customerRespository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Renew(int customerId)
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCustomer(CustomerSubscription customerSubscription)
        {
            var addedCustomer = _customerRespository.AddCustomer(customerSubscription);
            // return View("Views/RegisterCustomer/CustomerDetail.cshtml", addedCustomer);
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        }
    }
}

SubscriptionTracker/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SubscriptionTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SubscriptionTracker.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IExpenseRepository _expenseRepository;

        public ReportsController(IExpenseRepository expenseRepository)
        {
            _expenseRepository = expenseRepository;
        }

        public IActionResult Expense()
        {
            return View();
        }

        public IActionResult Customer()
        {
            return View();
        }

        public IActionResult Fees()
        {
            return View();
        }

        [HttpGet]
        [Produces("application/json")]
        public IActionResult GetCustomerJoiningReport([FromQuery] string fromDate, [FromQuery] string toDate)
        {
            var data = _expenseRepository.GetCustomerJoiningReport(Convert.ToDateTime(fromDate), Convert.ToDateTime(toDate)).ToList();
            return Json(JsonConvert.SerializeObject(data));
        }

        [HttpGet]
        [Produces("application/json")]
        public IActionResult GetFeesReport([FromQuery] string fromDate, [FromQuery] string toDate)
        {
            var data = _expenseRepository.GetFeesReport(Convert.ToDateTime(fromDate), Convert.ToDateTime(toDate)).ToList();
            return Json(JsonConvert.SerializeObject(data));
        }

        [HttpGet]
        [Produces("application/json")]
        public IActionResult GetExpenseReport([FromQuery] string fromDate, [FromQuery] string toDate)
        {
            var data = _expenseRepository.GetExpenseReport(Convert.ToDateTime(fromDate), Convert.ToDateTime(toDate)).ToList();
            return Json(JsonConvert.SerializeObject(data));
        }
    }
}

SubscriptionTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
    <title>Optimus Fitness</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>

                        <li><a asp-controller="RegisterCustomer" asp-action="Index">Customer Registration</a></li>
                        <li><a asp-controller="Expense" asp-action="Index">Add Expense</a></li>
                        <li><a asp-controller="Home" asp-action="GetAllCustomers">View Customers</a></li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="nav-label">Reports</span><span class="caret"></span></a>
                            <ul class="dropdown-menu">

                                <li><a style="color:black" asp-controller="Reports" asp-action="Expense">Expense</a></li>
                                <li><a style="color:black" asp-controller="Reports" asp-action="Customer">Customer</a></li>
                                <li><a style="color:black" asp-controller="Reports" asp-action="Fees">Fees</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="=row">
            <div class="col-md-3">
                <p class="lead">
                    <img style="border-radius:60%" class="img-responsive" src="~/Images/optimuslogo.png" />
                </p>
            </div>

            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>